name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for outlining this issue ! the maintainer will get in touch with you shortly :)'
        pr-message: 'Thank you for your first PR! The maintainer will get in touch with you shortly :)'
